### ISSUE TITLE
Where are the sources and project files of the GoboLinux mascot and documented complete mascot definition?

### ISSUE THREAD

**Issue by BoQsc** [gobolinux/Documentation#10]

**Comment by waldyrious** [comment]
Here are some relevant resources:

- [icon_mascot.svg](https://github.com/gobolinux/gobolinux.org/blob/master/images/icon_mascot.svg) at the https://github.com/gobolinux/gobolinux.org repo
- [que.png](https://github.com/gobolinux/Installer/blob/1c6b20230b515a78870ae56de5b4d898e8e8a9f2/share/Installer/Images/que.png) at the https://github.com/gobolinux/Installer repo (an older version of the mascot, apparently)
- From [gobolinux.org/faq.html](https://github.com/gobolinux/gobolinux.org/blob/98ecae358fe6d5fc0e84a0ba486667190cdc921c/lang/en_US/pages/faq.html#L250):
  > **Who is the mascot? Is that Fibo?**
  >
  > No, the mascot is called Que. He's a penguin wearing Fibo's clothes. 
- From [gobolinux.org/releases.html](https://github.com/gobolinux/gobolinux.org/blob/98ecae358fe6d5fc0e84a0ba486667190cdc921c/lang/en_US/pages/releases.html):
  > GoboLinux 011 was launched to coincide with the V International Forum on Free Software,
which take place in June 2004 in Porto Alegre, Brazil. Hisham designed a T-shirt to be 
sold at the event. He wanted a design that reminisced the World War II propaganda posters
(one of André's subjects of interest). The result was a vectorized mascot in a "We want
you" pose, and the line "GoboLinux - join the revolution". Rafael adapted it into the
release icon.
  >
  > For GoboLinux 012, the vectorized Que is featured again. André asked for
a suggestion for the release image, and Hisham said "I don't know, something that
took a long time but now is complete", in an allusion to the long delays in the
development of that particular release. André took matters with his own hands and
did the cool sith mascot. Nothing could be more apropriate, since GoboLinux 012
was released around the time Episode III came out, and indeed the Star Wars saga
took a long time to be done but was now complete.
  >
  > Version 013 was almost released without an image, as it was late in the night while we tried to
match our self-imposed deadline and everyone was so tired. Also, the site was redesigned for this
release, like on 010, so we even had a suitable excuse. ;) But since we worked so hard to make
this release as complete as possible, such detail could not be left behind. So Hisham made a
sketch of the mascot in the style of the new icons of the website.

**Comment by Nuc1eoN** [comment]
I think @waldyrious has answered the question? In the future consider asking in our [forums ](https://gobolinux.discourse.group/):)

Closing for now, but feel free to reopen if the question has not been answered to your satisfaction.
