### ISSUE TITLE
USB

### ISSUE THREAD

**Issue by mathiasrw** [gobolinux/Documentation#18]
Is there any good places to find out how I best install gobo on a usb? I can load it on to the USB but when I run it I cant install it on the same USB. Wondering if I need 2 usbs to do that...

**Comment by lucasvr** [comment]
Hi, Matthias. It's not possible to install it on the same USB; the installer has an explicit check to prevent the distro from being installed into the same source media (so that users don't accidentally overwrite the source partition and/or the Live USB boot sector). It should be OK to install it on a separate USB, though. It's been a long time since I last attempted to do that, but I can't think of any reasons why it wouldn't work.

**Comment by lucasvr** [comment]
By the way, please have a look at our list of [known issues](https://github.com/gobolinux/Documentation/wiki/GoboLinux-017-Known-Issues-and-Fixes) prior to testing the distro. You may also want to [join our forum](https://gobolinux.discourse.group/) for an improved communication. I will close this issue now -- thanks for getting in touch. If you find any problems running from USB after install, please feel free to reopen.
